export const features = [
  {
    value: "Toepassing",
    label: "Toepassing",
    type: "String",
    toCompare: "true",
  },
  {
    value: "salePrice",
    label: "Sale price",
    type: "Float",
    toCompare: "false",
  },
  {
    value: "manufacturerName",
    label: "Manufacturer name",
    type: "String",
    toCompare: "false",
  },
  { value: "Hardheid", label: "Hardheid", type: "String", toCompare: "true" },
  {
    value: "grossPrice",
    label: "Gross price",
    type: "String",
    toCompare: "false",
  },
  { value: "BUP_UOM", label: "BUP_UOM", type: "String", toCompare: "false" },
  {
    value: "Artikelnummer",
    label: "Artikel nummer",
    type: "String",
    toCompare: "true",
  },
  {
    value: "stepQuantity",
    label: "Step Quantity",
    type: "String",
    toCompare: "true",
  },
  {
    value: "BUP_Value",
    label: "BUP_Value",
    type: "String",
    toCompare: "false",
  },
  //{ value: "badges", label: "Keurmerk", type: "String" },
  { value: "uom", label: "Uom", type: "String", toCompare: "true" },
  { value: "Kleur", label: "Kleur", type: "String", toCompare: "true" },
  {
    value: "Temperatuurgebied",
    label: "Temperatuur gebied",
    type: "String",
    toCompare: "true",
  },
  {
    value: "BUP_Conversion",
    label: "BUP_Conversion",
    type: "String",
    toCompare: "false",
  },
  {
    value: "minQuantity",
    label: "Min quantity",
    type: "String",
    toCompare: "false",
  },
  { value: "Materiaal", label: "Materiaal", type: "String", toCompare: "true" },
  { value: "sku", label: "Sku", type: "String", toCompare: "false" },
  {
    value: "Snoerdikte",
    label: "Snoerdikte",
    type: "String",
    toCompare: "true",
  },
  {
    value: "Inwendige diameter",
    label: "Inwendige diameter",
    type: "String",
    toCompare: "true",
  },
  {
    value: "Maat volgens AS568",
    label: "Maat volgens AS568",
    type: "String",
    toCompare: "true",
  },
  {
    value: "listPrice",
    label: "List price",
    type: "String",
    toCompare: "false",
  },
  { value: "channel", label: "Channel", type: "String", toCompare: "false" },
  { value: "display", label: "Display", type: "String", toCompare: "false" },
];

export const MAX_PRODUCTS_TO_COMPARE = 4;
