const products = [
  {
    Toepassing: "Voedsel en dranken",
    salePrice: "1.41",
    manufacturerName: "",
    Hardheid: "70",
    grossPrice: "1.71",
    BUP_UOM: "",
    Artikelnummer: "115E19",
    stepQuantity: "5",
    BUP_Value: "",
    badges:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/omega-slang-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/o-t-symbol-icon-nl.jpg",
    uom: "Stuk",
    Kleur: "Zwart",
    productImage:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb/hlr-system/egt/pubnl/industriele slangen/rubber slangen/chemieslangen/rubber-chemieslang-rx-ultrafixx-md-pinl-nl.jpg",
    Temperatuurgebied: "van  -50  tot  150",
    BUP_Conversion: "",
    minQuantity: "5",
    manufacturerImage: "",
    name:
      "O-ring EPDM 70 shore - Voedsel (Binnen Ø=1.25 Snoer Ø=2.62; AS568- 102)",
    Materiaal: "EPDM",
    sku: "115E19",
    Snoerdikte: "2.62",
    "Inwendige diameter": "1.25",
    "Maat volgens AS568": "102",
    listPrice: "1.41",
    channel: "nl_NL",
    display: true,
    atp: {},
  },
  {
    Toepassing: "Voedsel en dranken",
    salePrice: "0.66",
    manufacturerName: "",
    Hardheid: "70",
    grossPrice: "0.80",
    BUP_UOM: "",
    Artikelnummer: "11545A",
    stepQuantity: "5",
    BUP_Value: "",
    badges:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/omega-slang-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/o-t-symbol-icon-nl.jpg",
    uom: "Stuk",
    Kleur: "Zwart",
    productImage:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb/hlr-system/egt/pubnl/industriele slangen/rubber slangen/chemieslangen/rubber-chemieslang-rx-ultrafixx-md-pinl-nl.jpg",
    Temperatuurgebied: "van  -50  tot  150",
    BUP_Conversion: "",
    minQuantity: "5",
    manufacturerImage: "",
    name:
      "O-ring EPDM 70 shore - Voedsel (Binnen Ø=1.78 Snoer Ø=1.78; AS568- 004)",
    Materiaal: "EPDM",
    sku: "11545A",
    Snoerdikte: "1.78",
    "Inwendige diameter": "1.78",
    "Maat volgens AS568": "4",
    listPrice: "0.66",
    channel: "nl_NL",
    display: true,
    atp: {},
  },
  {
    Toepassing: "Voedsel en dranken",
    salePrice: "1.36",
    manufacturerName: "",
    Hardheid: "70",
    grossPrice: "1.65",
    BUP_UOM: "",
    Artikelnummer: "115E1A",
    stepQuantity: "5",
    BUP_Value: "",
    badges:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/omega-slang-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/o-t-symbol-icon-nl.jpg",
    uom: "Stuk",
    Kleur: "Zwart",
    productImage:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb/hlr-system/blickle/internet images/lrxa-po_76g-fi_754998.jpg",
    Temperatuurgebied: "van  -50  tot  150",
    BUP_Conversion: "",
    minQuantity: "5",
    manufacturerImage: "",
    name:
      "O-ring EPDM 70 shore - Voedsel (Binnen Ø=2.06 Snoer Ø=2.62; AS568- 103)",
    Materiaal: "EPDM",
    sku: "115E1A",
    Snoerdikte: "2.62",
    "Inwendige diameter": "2.06",
    "Maat volgens AS568": "103",
    listPrice: "1.36",
    channel: "nl_NL",
    display: true,
    atp: {},
  },
  {
    Toepassing: "Voedsel en dranken",
    salePrice: "0.66",
    manufacturerName: "",
    Hardheid: "70",
    grossPrice: "0.80",
    BUP_UOM: "",
    Artikelnummer: "115576",
    stepQuantity: "5",
    BUP_Value: "",
    badges:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/rohs-icon-nl.jpg|https://eriksdigitalcdn.azureedge.net/shop/thumb40/hlr-system/egt/pubnl/pim_icons/o-t-symbol-icon-nl.jpg",
    uom: "Stuk",
    Kleur: "Zwart",
    productImage:
      "https://eriksdigitalcdn.azureedge.net/shop/thumb/hlr-system/webshop/grs/grs-product-images/grs10/10775_fot_012.jpg",
    Temperatuurgebied: "van  -50  tot  150",
    BUP_Conversion: "",
    minQuantity: "5",
    manufacturerImage: "",
    name:
      "O-ring EPDM 70 shore - Voedsel (Binnen Ø=2.9 Snoer Ø=1.78; AS568- 006)",
    Materiaal: "EPDM",
    sku: "115576",
    Snoerdikte: "1.78",
    "Inwendige diameter": "2.9",
    "Maat volgens AS568": "6",
    listPrice: "0.66",
    channel: "nl_NL",
    display: true,
    atp: {},
  },
];
export default products;

export const features = {
  Toepassing: "Toepassing",
  salePrice: "Sale price",
  manufacturerName: "Manufacturer name",
  Hardheid: "Hardheid",
  grossPrice: "grossPrice",
  BUP_UOM: "BUP_UOM",
  Artikelnummer: "Artikelnummer",
  stepQuantity: "stepQuantity",
  BUP_Value: "BUP_Value",
  //badges: "Keurmerk",
  uom: "uom",
  Kleur: "Kleur",
  //productImage: "productImage",
  Temperatuurgebied: "Temperatuurgebied",
  BUP_Conversion: "BUP_Conversion",
  minQuantity: "minQuantity",
  //manufacturerImage: "manufacturerImage",
  //name: "name",
  Materiaal: "Materiaal",
  sku: "sku",
  Snoerdikte: "Snoerdikte",
  "Inwendige diameter": "Inwendige diameter",
  "Maat volgens AS568": "Maat volgens AS568",
  listPrice: "listPrice",
  channel: "channel",
  display: "display",
  //atp: "atp",
};
